/**
 * TypeScript model emitter (ts-morph based).
 *
 * Emits schema definitions as TypeScript interfaces, type aliases,
 * and enums using ts-morph AST construction.
 */

import { pascalCase } from 'change-case';
import {
  Project,
  type OptionalKind,
  type PropertySignatureStructure,
  type SourceFile,
} from 'ts-morph';
import type { EnrichedSDKIR, SchemaDefinition, SchemaProperty } from '../../types/ir.js';
import type { EmittedFile } from '../../pipeline/write.js';

export function emitTypeScriptModels(
  enriched: EnrichedSDKIR,
  outputDir: string,
): { files: EmittedFile[]; domainTypeFiles: string[] } {
  const project = new Project({ useInMemoryFileSystem: true, skipAddingFilesFromTsConfig: true });
  const files: EmittedFile[] = [];

  const domainSchemas = new Map<string, SchemaDefinition[]>();
  const globalSchemas: SchemaDefinition[] = [];
  const schemasByName = new Map(enriched.schemas.map((s) => [s.name, s]));
  const knownSchemaNames = new Set(enriched.schemas.map((s) => s.name));

  for (const schema of enriched.schemas) {
    if (schema.ownership?.kind === 'external') continue;
    const domainFile = schema.ownership?.domainFile;
    if (domainFile) {
      if (!domainSchemas.has(domainFile)) domainSchemas.set(domainFile, []);
      domainSchemas.get(domainFile)!.push(schema);
      continue;
    }
    globalSchemas.push(schema);
  }

  // Global models file
  const modelsPath = `${outputDir}/src/types/models.ts`;
  const modelsFile = project.createSourceFile(modelsPath, '', { overwrite: true });
  const globalSchemaNames = new Set(globalSchemas.map((s) => s.name));
  addFilePreamble(
    modelsFile,
    collectTypeImportStatements(globalSchemas, { kind: 'models' }, schemasByName, knownSchemaNames),
  );
  const globalContext = createEmitContext(modelsFile, globalSchemaNames);

  for (const name of enriched.schemaOrder) {
    const schema = schemasByName.get(name);
    if (!schema || !globalSchemaNames.has(name)) continue;
    const decision = enriched.renderDecisions[name];
    if (decision === 'skip') continue;
    emitSchema(modelsFile, schema, globalContext);
  }

  for (const schema of globalSchemas) {
    if (enriched.schemaOrder.includes(schema.name)) continue;
    const decision = enriched.renderDecisions[schema.name];
    if (decision === 'skip') continue;
    emitSchema(modelsFile, schema, globalContext);
  }

  files.push({ relativePath: 'src/types/models.ts', content: modelsFile.getFullText() });

  // Per-domain type files
  const domainTypeFiles: string[] = [];
  for (const [domainFile, schemas] of domainSchemas) {
    const filePath = `${outputDir}/src/types/${domainFile}.ts`;
    const sourceFile = project.createSourceFile(filePath, '', { overwrite: true });
    addFilePreamble(
      sourceFile,
      collectTypeImportStatements(schemas, { kind: 'domain', domainFile }, schemasByName, knownSchemaNames),
    );
    const domainContext = createEmitContext(sourceFile, new Set(schemas.map((s) => s.name)));
    for (const schema of schemas) {
      const decision = enriched.renderDecisions[schema.name];
      if (decision === 'skip') continue;
      emitSchema(sourceFile, schema, domainContext);
    }
    files.push({ relativePath: `src/types/${domainFile}.ts`, content: sourceFile.getFullText() });
    domainTypeFiles.push(domainFile);
  }

  return { files, domainTypeFiles: domainTypeFiles.sort() };
}

// ── Internal types ───────────────────────────────────────────────────────────

interface EmitContext {
  readonly sourceFile: SourceFile;
  readonly reservedNames: Set<string>;
}

interface FileTarget {
  readonly kind: 'models' | 'domain';
  readonly domainFile?: string;
}

interface ImportSpecifier {
  readonly importedName: string;
  readonly localName?: string;
}

function createEmitContext(sourceFile: SourceFile, reservedNames: Set<string>): EmitContext {
  return { sourceFile, reservedNames: new Set(reservedNames) };
}

function addFilePreamble(sourceFile: SourceFile, importStatements: string[]): void {
  sourceFile.addStatements([
    '// This file is auto-generated by Tesseract. Do not edit manually.',
    ...(importStatements.length > 0 ? ['', ...importStatements] : []),
    '',
  ]);
}

// ── Import statement collection ──────────────────────────────────────────────

function collectTypeImportStatements(
  schemas: SchemaDefinition[],
  target: FileTarget,
  schemasByName: ReadonlyMap<string, SchemaDefinition>,
  knownSchemaNames: ReadonlySet<string>,
): string[] {
  const localSchemaNames = new Set(schemas.map((s) => s.name));
  const importsByModule = new Map<string, ImportSpecifier[]>();

  for (const schema of schemas) {
    for (const reference of collectSchemaReferences(schema, knownSchemaNames)) {
      if (localSchemaNames.has(reference)) continue;
      const referencedSchema = schemasByName.get(reference);
      if (!referencedSchema) continue;

      if (referencedSchema.ownership?.kind === 'external') {
        const ei = referencedSchema.ownership.externalImport;
        if (!ei) continue;
        addImportSpecifier(importsByModule, ei.importPath, {
          importedName: ei.exportName,
          localName: referencedSchema.name !== ei.exportName ? referencedSchema.name : undefined,
        });
        continue;
      }

      const providerDomainFile = referencedSchema.ownership?.domainFile;
      if (!providerDomainFile) {
        if (target.kind === 'models') continue;
        addImportSpecifier(importsByModule, './models.js', { importedName: referencedSchema.name });
        continue;
      }

      if (target.kind === 'domain' && target.domainFile === providerDomainFile) continue;
      addImportSpecifier(importsByModule, `./${providerDomainFile}.js`, { importedName: referencedSchema.name });
    }
  }

  return [...importsByModule.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([modulePath, specifiers]) => {
      const rendered = [...specifiers]
        .sort((a, b) => `${a.importedName}:${a.localName ?? ''}`.localeCompare(`${b.importedName}:${b.localName ?? ''}`))
        .map((s) => (s.localName ? `${s.importedName} as ${s.localName}` : s.importedName))
        .join(', ');
      return `import type { ${rendered} } from '${modulePath}';`;
    });
}

function collectSchemaReferences(schema: SchemaDefinition, knownSchemaNames: ReadonlySet<string>): Set<string> {
  const references = new Set<string>();
  if (schema.extends) collectTypeReferences(schema.extends, knownSchemaNames, references);
  if (schema.unionMembers) for (const m of schema.unionMembers) collectTypeReferences(m, knownSchemaNames, references);
  if (schema.intersectionMembers) for (const m of schema.intersectionMembers) collectTypeReferences(m, knownSchemaNames, references);
  if (schema.additionalPropertiesType) collectTypeReferences(schema.additionalPropertiesType, knownSchemaNames, references);
  for (const prop of schema.properties) collectTypeReferences(prop.type, knownSchemaNames, references);
  references.delete(schema.name);
  return references;
}

function collectTypeReferences(type: string, knownSchemaNames: ReadonlySet<string>, references: Set<string>): void {
  for (const match of type.matchAll(/\b[A-Za-z_$][\w$]*\b/g)) {
    if (knownSchemaNames.has(match[0])) references.add(match[0]);
  }
}

function addImportSpecifier(importsByModule: Map<string, ImportSpecifier[]>, modulePath: string, specifier: ImportSpecifier): void {
  const existing = importsByModule.get(modulePath);
  if (!existing) { importsByModule.set(modulePath, [specifier]); return; }
  if (!existing.some((e) => e.importedName === specifier.importedName && e.localName === specifier.localName)) {
    existing.push(specifier);
  }
}

// ── Schema emission ──────────────────────────────────────────────────────────

function emitSchema(sourceFile: SourceFile, schema: SchemaDefinition, context: EmitContext): void {
  if (schema.isEnum) emitEnum(sourceFile, schema);
  else if (schema.isTypeAlias || schema.isUnionType || schema.isIntersectionType) emitTypeAlias(sourceFile, schema, context);
  else emitInterface(sourceFile, schema, context);
}

function emitEnum(sourceFile: SourceFile, schema: SchemaDefinition): void {
  const values = schema.enumValues ?? [];
  if (values.length === 0) return;
  const allStrings = values.every((v) => typeof v === 'string');

  if (allStrings) {
    const members = values.map((v) => {
      const key = String(v).replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1').toUpperCase();
      return `  ${key}: ${JSON.stringify(v)}`;
    });
    const doc = schema.description ? `/** ${schema.description} */\n` : '';
    sourceFile.addStatements(`${doc}export const ${schema.name} = {\n${members.join(',\n')}\n} as const;\n`);
    sourceFile.addStatements(`export type ${schema.name} = (typeof ${schema.name})[keyof typeof ${schema.name}];\n`);
    return;
  }

  const members = values.map((v) => ({
    name: `VALUE_${String(v).replace(/[^a-zA-Z0-9_]/g, '_')}`,
    value: typeof v === 'string' ? JSON.stringify(v) : String(v),
  }));
  sourceFile.addEnum({
    name: schema.name,
    isExported: true,
    docs: schema.description ? [schema.description] : [],
    members: members.map((m) => ({ name: m.name, value: m.value })),
  });
}

function emitTypeAlias(sourceFile: SourceFile, schema: SchemaDefinition, context: EmitContext): void {
  let type: string;
  if (schema.isUnionType && schema.unionMembers?.length) {
    type = schema.unionMembers.map((m, i) => hoistInlineTypes(m, `${schema.name}Variant${i + 1}`, context)).join(' | ');
  } else if (schema.isIntersectionType && schema.intersectionMembers?.length) {
    type = schema.intersectionMembers.map((m, i) => hoistInlineTypes(m, `${schema.name}Part${i + 1}`, context)).join(' & ');
  } else if (schema.additionalPropertiesType) {
    type = `Record<string, ${hoistInlineTypes(schema.additionalPropertiesType, `${schema.name}Value`, context)}>`;
  } else { type = 'unknown'; }

  sourceFile.addTypeAlias({
    name: schema.name, isExported: true, type,
    docs: schema.description ? [schema.description] : [],
  });
}

function emitInterface(sourceFile: SourceFile, schema: SchemaDefinition, context: EmitContext): void {
  const props = schema.properties.map((p) => buildPropertySignature(schema.name, p, context));
  const decl = sourceFile.addInterface({
    name: schema.name, isExported: true,
    docs: schema.description ? [schema.description] : [],
    extends: schema.extends ? [schema.extends] : [],
    properties: props,
  });
  if (schema.additionalPropertiesType) {
    decl.addIndexSignature({
      keyName: 'key', keyType: 'string',
      returnType: hoistInlineTypes(schema.additionalPropertiesType, `${schema.name}Value`, context),
    });
  }
}

function buildPropertySignature(
  ownerName: string, prop: SchemaProperty, context: EmitContext,
): OptionalKind<PropertySignatureStructure> {
  const docs: string[] = [];
  if (prop.description) docs.push(prop.description);
  if (prop.deprecated) docs.push('@deprecated');
  if (prop.defaultValue !== undefined) docs.push(`@default ${JSON.stringify(prop.defaultValue)}`);
  const rawType = prop.nullable ? `${prop.type} | null` : prop.type;
  return {
    name: prop.name,
    type: hoistInlineTypes(rawType, `${ownerName}${pascalCase(prop.name)}`, context),
    hasQuestionToken: !prop.required,
    isReadonly: prop.readOnly ?? false,
    docs,
  };
}

// ── Inline type hoisting ─────────────────────────────────────────────────────

function hoistInlineTypes(type: string, preferredName: string, context: EmitContext): string {
  const trimmed = type.trim();
  if (!trimmed) return trimmed;

  const unionMembers = splitTopLevel(trimmed, '|');
  if (unionMembers.length > 1) {
    const nullable = unionMembers.filter((m) => m === 'null' || m === 'undefined');
    const nonNullable = unionMembers.filter((m) => m !== 'null' && m !== 'undefined');
    if (nonNullable.length === 1 && nullable.length > 0) {
      return [hoistInlineTypes(nonNullable[0], preferredName, context), ...nullable].join(' | ');
    }
    return unionMembers.map((m, i) => hoistInlineTypes(m, `${preferredName}Option${i + 1}`, context)).join(' | ');
  }

  const interMembers = splitTopLevel(trimmed, '&');
  if (interMembers.length > 1) {
    return interMembers.map((m, i) => hoistInlineTypes(m, `${preferredName}Part${i + 1}`, context)).join(' & ');
  }

  if (isWrappedBy(trimmed, '(', ')'))
    return `(${hoistInlineTypes(trimmed.slice(1, -1), preferredName, context)})`;

  if (trimmed.endsWith('[]')) {
    const inner = hoistInlineTypes(trimmed.slice(0, -2), `${preferredName}Item`, context);
    return needsParens(inner) ? `(${inner})[]` : `${inner}[]`;
  }

  const arrayArgs = parseGenericArgs(trimmed, 'Array');
  if (arrayArgs) return `Array<${hoistInlineTypes(arrayArgs[0], `${preferredName}Item`, context)}>`;

  const recordArgs = parseGenericArgs(trimmed, 'Record');
  if (recordArgs) return `Record<${recordArgs[0]}, ${hoistInlineTypes(recordArgs[1], `${preferredName}Value`, context)}>`;

  if (isWrappedBy(trimmed, '{', '}')) return emitInlineInterface(trimmed, preferredName, context);

  return trimmed;
}

function emitInlineInterface(typeLiteral: string, preferredName: string, context: EmitContext): string {
  const members = parseInlineMembers(typeLiteral);
  const interfaceName = reserveName(preferredName, context.reservedNames);
  const properties: OptionalKind<PropertySignatureStructure>[] = [];
  let indexSig: { keyName: string; keyType: string; type: string } | undefined;

  for (const member of members) {
    if (member.kind === 'index') {
      indexSig = { ...member, type: hoistInlineTypes(member.type, `${interfaceName}Value`, context) };
      continue;
    }
    properties.push({
      name: member.name,
      type: hoistInlineTypes(member.type, `${interfaceName}${pascalCase(member.name)}`, context),
      hasQuestionToken: member.optional,
      isReadonly: member.readonly,
    });
  }

  const decl = context.sourceFile.addInterface({ name: interfaceName, isExported: true, properties });
  if (indexSig) decl.addIndexSignature({ keyName: indexSig.keyName, keyType: indexSig.keyType, returnType: indexSig.type });
  return interfaceName;
}

interface ParsedPropertyMember { kind: 'property'; name: string; optional: boolean; readonly: boolean; type: string }
interface ParsedIndexMember { kind: 'index'; keyName: string; keyType: string; type: string }
type ParsedInlineMember = ParsedPropertyMember | ParsedIndexMember;

function parseInlineMembers(typeLiteral: string): ParsedInlineMember[] {
  const body = typeLiteral.slice(1, -1).trim();
  if (!body) return [];
  return splitTopLevel(body, ';').map((s) => s.trim()).filter(Boolean).map(parseInlineMember);
}

function parseInlineMember(segment: string): ParsedInlineMember {
  const indexMatch = segment.match(/^\[\s*([^:]+):\s*([^\]]+)\]\s*:\s*(.+)$/);
  if (indexMatch) return { kind: 'index', keyName: indexMatch[1].trim(), keyType: indexMatch[2].trim(), type: indexMatch[3].trim() };
  const propMatch = segment.match(/^(readonly\s+)?([A-Za-z_$][\w$]*|"[^"]+"|'[^']+')(?:(\?))?\s*:\s*(.+)$/);
  if (!propMatch) throw new Error(`Unsupported inline object member: ${segment}`);
  return { kind: 'property', name: propMatch[2].replace(/^['"]|['"]$/g, ''), optional: propMatch[3] === '?', readonly: Boolean(propMatch[1]), type: propMatch[4].trim() };
}

// ── Parser utilities ─────────────────────────────────────────────────────────

function parseGenericArgs(type: string, genericName: string): string[] | undefined {
  const prefix = `${genericName}<`;
  if (!type.startsWith(prefix) || !type.endsWith('>')) return undefined;
  return splitTopLevel(type.slice(prefix.length, -1), ',').map((p) => p.trim()).filter(Boolean);
}

function splitTopLevel(input: string, separator: '|' | '&' | ';' | ','): string[] {
  const parts: string[] = [];
  let current = '';
  let curly = 0, angle = 0, paren = 0, bracket = 0;
  let quote: string | undefined;

  for (let i = 0; i < input.length; i++) {
    const ch = input[i];
    const prev = i > 0 ? input[i - 1] : undefined;
    if (quote) { current += ch; if (ch === quote && prev !== '\\') quote = undefined; continue; }
    if (ch === '\'' || ch === '"') { quote = ch; current += ch; continue; }
    switch (ch) { case '{': curly++; break; case '}': curly--; break; case '<': angle++; break; case '>': angle--; break; case '(': paren++; break; case ')': paren--; break; case '[': bracket++; break; case ']': bracket--; break; }
    if (ch === separator && curly === 0 && angle === 0 && paren === 0 && bracket === 0) { parts.push(current.trim()); current = ''; continue; }
    current += ch;
  }
  if (current.trim()) parts.push(current.trim());
  return parts.length > 0 ? parts : [input.trim()];
}

function isWrappedBy(input: string, open: '{' | '(', close: '}' | ')'): boolean {
  if (!input.startsWith(open) || !input.endsWith(close)) return false;
  let depth = 0;
  let quote: string | undefined;
  for (let i = 0; i < input.length; i++) {
    const ch = input[i];
    const prev = i > 0 ? input[i - 1] : undefined;
    if (quote) { if (ch === quote && prev !== '\\') quote = undefined; continue; }
    if (ch === '\'' || ch === '"') { quote = ch; continue; }
    if (ch === open) depth++;
    if (ch === close) depth--;
    if (depth === 0 && i < input.length - 1) return false;
  }
  return depth === 0;
}

function needsParens(type: string): boolean {
  return type.includes(' | ') || type.includes(' & ');
}

function reserveName(preferredName: string, reservedNames: Set<string>): string {
  let candidate = preferredName;
  let counter = 2;
  while (reservedNames.has(candidate)) { candidate = `${preferredName}${counter}`; counter++; }
  reservedNames.add(candidate);
  return candidate;
}
