/**
 * Orchestration layer for TypeScript model emission.
 */

import { Project } from "ts-morph";
import { EmittedFile } from "../../../pipeline/write.js";
import { EnrichedSDKIR, SchemaDefinition } from "../../../types/ir.js";
import { createEmitContext, emitSchema } from "./emitSchema.js";
import { collectTypeImportStatements } from "./importCollector.js";

export function emitTypeScriptModels(
  enriched: EnrichedSDKIR,
  outputDir: string,
): { files: EmittedFile[]; domainTypeFiles: string[] } {
  const project = new Project({
    useInMemoryFileSystem: true,
    skipAddingFilesFromTsConfig: true,
  });

  const files: EmittedFile[] = [];

  const domainSchemas = new Map<string, SchemaDefinition[]>();
  const globalSchemas: SchemaDefinition[] = [];

  const schemasByName = new Map(enriched.schemas.map((s) => [s.name, s]));
  const knownSchemaNames = new Set(enriched.schemas.map((s) => s.name));

  for (const schema of enriched.schemas) {
    if (schema.ownership?.kind === "external") continue;

    const domainFile = schema.ownership?.domainFile;
    if (domainFile) {
      if (!domainSchemas.has(domainFile)) domainSchemas.set(domainFile, []);
      domainSchemas.get(domainFile)!.push(schema);
    } else {
      globalSchemas.push(schema);
    }
  }

  const modelsPath = `${outputDir}/src/types/models.ts`;
  const modelsFile = project.createSourceFile(modelsPath, "", {
    overwrite: true,
  });

  const globalSchemaNames = new Set(globalSchemas.map((s) => s.name));

  modelsFile.addStatements([
    "// This file is auto-generated by Tesseract. Do not edit manually.",
    "",
    ...collectTypeImportStatements(
      globalSchemas,
      schemasByName,
      knownSchemaNames,
    ),
    "",
  ]);

  const globalCtx = createEmitContext(modelsFile, globalSchemaNames);

  for (const schema of globalSchemas) {
    if (enriched.renderDecisions[schema.name] === "skip") continue;
    emitSchema(modelsFile, schema, globalCtx);
  }

  files.push({
    relativePath: "src/types/models.ts",
    content: modelsFile.getFullText(),
  });

  const domainTypeFiles: string[] = [];

  for (const [domainFile, schemas] of domainSchemas) {
    const filePath = `${outputDir}/src/types/${domainFile}.ts`;
    const sourceFile = project.createSourceFile(filePath, "", {
      overwrite: true,
    });

    const domainNames = new Set(schemas.map((s) => s.name));

    sourceFile.addStatements([
      "// This file is auto-generated by Tesseract. Do not edit manually.",
      "",
      ...collectTypeImportStatements(schemas, schemasByName, knownSchemaNames),
      "",
    ]);

    const ctx = createEmitContext(sourceFile, domainNames);

    for (const schema of schemas) {
      if (enriched.renderDecisions[schema.name] === "skip") continue;
      emitSchema(sourceFile, schema, ctx);
    }

    files.push({
      relativePath: `src/types/${domainFile}.ts`,
      content: sourceFile.getFullText(),
    });

    domainTypeFiles.push(domainFile);
  }

  return {
    files,
    domainTypeFiles: domainTypeFiles.sort(),
  };
}
